apiVersion: security.liqo.io/v1
kind: PeeringSecurity
metadata:
  name: example-peeringsecurity
  namespace: liqo-tenant-rome
spec:
  rules:
    - source: remote-cluster
      destination: offloaded
      allow: true
    - source: remote-cluster
      allow: false
