apiVersion: security.liqo.io/v1
kind: PeeringConnectivity
metadata:
  name: milan
  namespace: liqo-tenant-milan
spec:
  rules:
    - source: vc-remote
      action: "allow"
    - source: remote-cluster
      action: "deny"
