apiVersion: security.liqo.io/v1
kind: PeeringConnectivity
metadata:
  name: rome
  namespace: liqo-tenant-rome
spec:
  rules:
    - source: remote-cluster
      destination: offloaded
      allow: true
    - source: offloaded
      destination: remote-cluster
      allow: true
    - source: offloaded
      allow: false
    - source: remote-cluster
      allow: false
